-- MySQL Script generated by MySQL Workbench
-- Mon Feb 27 17:27:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nilaikdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nilaikdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nilaikdb` DEFAULT CHARACTER SET utf8 ;
USE `nilaikdb` ;

-- -----------------------------------------------------
-- Table `nilaikdb`.`ImgProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nilaikdb`.`ImgProduto` (
  `idImgProduto` INT NOT NULL AUTO_INCREMENT,
  `Url` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idImgProduto`),
  UNIQUE INDEX `idImgProduto_UNIQUE` (`idImgProduto` ASC) VISIBLE,
  UNIQUE INDEX `Url_UNIQUE` (`Url` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nilaikdb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nilaikdb`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `Articulo` VARCHAR(50) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Talla` INT NOT NULL,
  `Codigo` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `PrecioMayoreo` INT NOT NULL,
  `PrecioMenudeo` INT NOT NULL,
  `Existencias` VARCHAR(45) NOT NULL,
  `ImgProduto_idImgProduto` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `ImgProduto_idImgProduto`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC) VISIBLE,
  UNIQUE INDEX `idProducto_UNIQUE` (`idProducto` ASC) VISIBLE,
  INDEX `fk_Producto_ImgProduto_idx` (`ImgProduto_idImgProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_ImgProduto`
    FOREIGN KEY (`ImgProduto_idImgProduto`)
    REFERENCES `nilaikdb`.`ImgProduto` (`idImgProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nilaikdb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nilaikdb`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `FechaDePedido` DATE NOT NULL,
  PRIMARY KEY (`idPedido`),
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nilaikdb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nilaikdb`.`carrito` (
  `idcarrito` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idcarrito`, `Pedido_idPedido`),
  INDEX `fk_carrito_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `nilaikdb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nilaikdb`.`Mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nilaikdb`.`Mensaje` (
  `idMensaje` INT NOT NULL,
  `Mensaje` VARCHAR(45) NOT NULL,
  `MailDeMensaje` VARCHAR(45) NOT NULL,
  `Visto` INT NOT NULL,
  PRIMARY KEY (`idMensaje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nilaikdb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nilaikdb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(150) NOT NULL,
  `Contrasena` VARCHAR(45) NOT NULL,
  `Nacimiento` DATE NOT NULL,
  `Direccion` VARCHAR(150) NOT NULL,
  `carrito_idcarrito` INT NOT NULL,
  `Mensaje_idMensaje` INT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) VISIBLE,
  INDEX `fk_Cliente_carrito1_idx` (`carrito_idcarrito` ASC) VISIBLE,
  INDEX `fk_Cliente_Mensaje1_idx` (`Mensaje_idMensaje` ASC) VISIBLE,
  INDEX `fk_Cliente_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_carrito1`
    FOREIGN KEY (`carrito_idcarrito`)
    REFERENCES `nilaikdb`.`carrito` (`idcarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Mensaje1`
    FOREIGN KEY (`Mensaje_idMensaje`)
    REFERENCES `nilaikdb`.`Mensaje` (`idMensaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `nilaikdb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nilaikdb`.`Envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nilaikdb`.`Envio` (
  `idenvio` INT NOT NULL AUTO_INCREMENT,
  `FechaDeSalida` DATE NOT NULL,
  `FechaDeEntrega` DATE NOT NULL,
  `FechaDeEnvio` DATE NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idenvio`, `Pedido_idPedido`),
  INDEX `fk_Envio_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Envio_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `nilaikdb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nilaikdb`.`Producto_has_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nilaikdb`.`Producto_has_Pedido` (
  `Producto_idProducto` INT NOT NULL,
  `Producto_ImgProduto_idImgProduto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Producto_ImgProduto_idImgProduto`, `Pedido_idPedido`),
  INDEX `fk_Producto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Producto_has_Pedido_Producto1_idx` (`Producto_idProducto` ASC, `Producto_ImgProduto_idImgProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Pedido_Producto1`
    FOREIGN KEY (`Producto_idProducto` , `Producto_ImgProduto_idImgProduto`)
    REFERENCES `nilaikdb`.`Producto` (`idProducto` , `ImgProduto_idImgProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `nilaikdb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
