-- MySQL Script generated by MySQL Workbench
-- Sat Feb 25 11:40:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ImgProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ImgProduto` (
  `idImgProduto` INT NOT NULL AUTO_INCREMENT,
  `Url` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idImgProduto`),
  UNIQUE INDEX `idImgProduto_UNIQUE` (`idImgProduto` ASC) VISIBLE,
  UNIQUE INDEX `Url_UNIQUE` (`Url` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `Articulo` VARCHAR(50) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Talla` INT NULL,
  `Codigo` VARCHAR(45) NULL,
  `Color` VARCHAR(45) NULL,
  `PrecioMayoreo` INT NULL,
  `PrecioMenudeo` INT NULL,
  `Existencias` VARCHAR(45) NULL,
  `ImgProduto_idImgProduto` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `ImgProduto_idImgProduto`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC) VISIBLE,
  UNIQUE INDEX `idProducto_UNIQUE` (`idProducto` ASC) VISIBLE,
  INDEX `fk_Producto_ImgProduto_idx` (`ImgProduto_idImgProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_ImgProduto`
    FOREIGN KEY (`ImgProduto_idImgProduto`)
    REFERENCES `mydb`.`ImgProduto` (`idImgProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `FechaDePedido` DATE NULL,
  PRIMARY KEY (`idPedido`),
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido_has_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido_has_Producto` (
  `Pedido_idPedido` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Producto_ImgProduto_idImgProduto` INT NOT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Producto_idProducto`, `Producto_ImgProduto_idImgProduto`),
  INDEX `fk_Pedido_has_Producto_Producto1_idx` (`Producto_idProducto` ASC, `Producto_ImgProduto_idImgProduto` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Producto_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Producto_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto` , `Producto_ImgProduto_idImgProduto`)
    REFERENCES `mydb`.`Producto` (`idProducto` , `ImgProduto_idImgProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrito` (
  `idcarrito` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idcarrito`, `Pedido_idPedido`),
  INDEX `fk_carrito_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(150) NOT NULL,
  `Contrasena` VARCHAR(45) NOT NULL,
  `Nacimiento` DATE NOT NULL,
  `Direccion` VARCHAR(150) NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `carrito_idcarrito` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Pedido_idPedido`, `carrito_idcarrito`),
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) VISIBLE,
  INDEX `fk_Cliente_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Cliente_carrito1_idx` (`carrito_idcarrito` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_carrito1`
    FOREIGN KEY (`carrito_idcarrito`)
    REFERENCES `mydb`.`carrito` (`idcarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensaje` (
  `idMensaje` INT NOT NULL,
  `Mensaje` VARCHAR(45) NOT NULL,
  `MailDeMensaje` VARCHAR(45) NOT NULL,
  `Visto` INT NOT NULL,
  PRIMARY KEY (`idMensaje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Envio` (
  `idenvio` INT NOT NULL AUTO_INCREMENT,
  `FechaDeSalida` DATE NOT NULL,
  `FechaDeEntrega` DATE NOT NULL,
  `FechaDeEnvio` DATE NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idenvio`, `Pedido_idPedido`),
  INDEX `fk_Envio_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Envio_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensaje_has_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensaje_has_Cliente` (
  `Mensaje_idMensaje` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Cliente_Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`Mensaje_idMensaje`, `Cliente_idCliente`, `Cliente_Pedido_idPedido`),
  INDEX `fk_Mensaje_has_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC, `Cliente_Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Mensaje_has_Cliente_Mensaje1_idx` (`Mensaje_idMensaje` ASC) VISIBLE,
  CONSTRAINT `fk_Mensaje_has_Cliente_Mensaje1`
    FOREIGN KEY (`Mensaje_idMensaje`)
    REFERENCES `mydb`.`Mensaje` (`idMensaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensaje_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente` , `Cliente_Pedido_idPedido`)
    REFERENCES `mydb`.`Cliente` (`idCliente` , `Pedido_idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `mydb`.`ImgProduto` (`Url`)
VALUES ('https://ejemplo.com/img1.jpg');
INSERT INTO `mydb`.`Producto` (`Articulo`, `Marca`, `Talla`, `Codigo`, `Color`, `PrecioMayoreo`, `PrecioMenudeo`, `Existencias`, `ImgProduto_idImgProduto`)
VALUES ('Camiseta', 'Nike', 8, 'NKN001', 'Negro', 100, 150, '10 unidades', 1);
INSERT INTO `mydb`.`Pedido` (`FechaDePedido`)
VALUES ('2023-02-25');
INSERT INTO `mydb`.`Pedido_has_Producto` (`Pedido_idPedido`, `Producto_idProducto`, `Producto_ImgProduto_idImgProduto`)
VALUES (1, 1, 1);
INSERT INTO `mydb`.`carrito` (`idcarrito`, `Pedido_idPedido`)
VALUES (1, 1);
INSERT INTO `mydb`.`Cliente` (`Nombre`, `Apellido`, `Correo`, `Contrasena`, `Nacimiento`, `Direccion`, `Pedido_idPedido`, `carrito_idcarrito`)
VALUES ('Juan', 'Pérez', 'juan.perez@ejemplo.com', 'contrasena', '2000-01-01', 'Av. Ejemplo 123', 1, 1);